
### Task 1. 
Create a NumPy array for:

salaries = [40000, 50000, 60000, 70000]

Print: shape, number of dimensions, data type


In [2]:
import numpy as np

In [3]:
salaries = [40000, 50000, 60000, 70000]

salaries_np = np.array(salaries)
salaries_np
print(salaries_np.shape, salaries_np.ndim, salaries_np.dtype)

(4,) 1 int64


### Task 2

Create a 2D array representing:

[age, salary]
[23, 40000]
[28, 52000]
[35, 75000]

Print: array, shape, ndim

In [ ]:
# Think of it as --> rows: people (each person/row is represeted by age, salary), 
# columns: features (each column is a feature, two columns--age, salary)

age_salaries = np.array([[23, 40000], [28, 52000], [35, 75000]])
age_salaries

print(age_salaries.ndim, age_salaries.shape)

2 (3, 2)


### Task 3

Create an array of:

10 zeros

10 ones

In [10]:
arr_z1 = np.zeros(10)
print(arr_z1)
arr_o1 = np.ones(10)
arr_o1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Task 4

Create numbers from 5 to 50 with step 5

In [13]:
arr_arng = np.arange(5,51,5)
arr_arng

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

### Task 5

Create 8 evenly spaced values between 0 and 100

In [8]:
arr_ls = np.linspace(1, 100, 8)
arr_ls

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

### Task 4 (Real-World)

Simulate 30 days temperature data:
- Mean = 25°C, 
- Std deviation = 3°C

In [12]:
# simulating temperature for 30 days with mean of 25°C, and deviation of 3°C
arr_tmp = np.random.normal(loc=25, scale=3, size=30)
print(arr_tmp)

[20.59841751 19.76534602 25.07046764 20.88318456 28.87017203 28.85921118
 29.2435287  27.61867562 26.29143367 22.52735946 27.94706749 25.54800487
 21.61322752 28.76462727 26.29397127 27.04700987 28.83134174 27.47969336
 23.66678069 25.55861945 22.4112352  27.34628257 26.11436173 23.67477375
 22.46011594 28.80304046 24.74332785 25.86497016 23.90178816 26.61771868]


In [22]:
# 2 weeks × 7 days × 2 cities
arr_w_d_city = np.random.normal(25, 3, (2, 7, 2))
arr_w_d_city
#print(arr_w_d_city.shape, arr_w_d_city.ndim)

array([[[29.96286998, 21.72575917],
        [26.31360313, 25.52867899],
        [24.60009643, 20.3213681 ],
        [26.32186129, 23.6559888 ],
        [24.93065827, 22.13314125],
        [26.10503732, 21.97632861],
        [23.10446435, 30.35811251]],

       [[23.64888644, 27.6325188 ],
        [25.13484221, 20.64738716],
        [25.50269738, 25.1500457 ],
        [25.30011067, 28.7589618 ],
        [29.63236875, 30.82747268],
        [24.81182213, 23.55819209],
        [22.77495077, 26.42763145]]])

### Task 6

    Create:
    arr = np.array([5, 10, 15, 20, 25, 30])
    Get last 3 elements
    Get elements at even indices
    Replace values > 20 with 0

#### Boolean Indexing Returns a Copy, Not a View
    Its example is shown below
    

In [ ]:
# ------------------

a = np.array([1, 2, 3, 4, 5, 6, 7])
b = a[1:4]
b[0] = 99
print(a)

#------------------



[ 1 99  3  4  5  6  7]
[20 25 30]
[ 5 15 25]
[25 30]
[ 5 10 15 20  0  0]


In [ ]:
# Boolean Indexing Returns a Copy, Not a View

arr1 = np.array([5, 10, 15, 20, 25, 30])
sub_arr1 = arr1[arr1>20] # Gives a copy not view
sub_arr1[::] = 0
print(arr1[arr1>20])
print(arr1) # Therefore array is not changed!

[25 30]
[ 5 10 15 20 25 30]


In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[-3:])
print(arr[::2])
print(arr[arr>20]) 
# Here we are printing a slice-(in terms of condition/boolean-mask, ie only that part where condition is True) of an array
arr[arr>20] = 0
# Here we are modifying arr by providing mask-in place ie without creating its copy
print(arr)

[20 25 30]
[ 5 15 25]
[25 30]
[ 5 10 15 20  0  0]


### Task 7 (2D)
data = np.array([
    [18, 20000],
    [25, 30000],
    [40, 50000],
    [30, 40000]
])

    Extract all ages
    Extract all salaries
    Extract rows where age > 30

In [ ]:
data = np.array([
    [18, 20000],
    [25, 30000],
    [40, 50000],
    [30, 40000]
])
filtered = data[data[:, 0]>30] # gives copy of data
print(filtered)
# print(data[:,0])
# print(data[:,1])
# print(data[data[:,0]>30]) # This changes original data, as boolean condition is used to make changes in-place, not in a copy
print(data)

[[   40 50000]]
[[   18 20000]
 [   25 30000]
 [   40 50000]
 [   30 40000]]


### Boolean Indexing Returns a Copy, Not a View

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25     # mask is an array of True/False
sub_arr = arr[arr>25]  #  sub_arr = arr[arr>25] Creates a mask/copy of arr, so original array is not modifies
print(sub_arr)
print(mask)

print(arr[mask])
print(arr)

[30 40 50]
[False False  True  True  True]
[30 40 50]
[10 20 30 40 50]


In [ ]:
salaries = np.array([25000, 40000, 55000, 70000])
high_salary = salaries > 50000
print(salaries[high_salary])  # Printing slice of salary
print(salaries)

salaries[salaries < 50000] *= 1.10  # modifying salaries in place with boolean masking
print(salaries)

[55000 70000]
[25000 40000 55000 70000]


In [ ]:
data = np.array([
        [22, 30000],
        [28, 45000],
        [35, 60000],
        [40, 80000]
    ])

# Filter rows where salary > 50000
high_income = data[data[:, 1] > 50000]
print(high_income)  # Copy of data
print(data)   # original data

# Increase salary for age > 30

# data = data.astype(float) # changing datatype of complete 2d array is possible

# data[:, 1] = data[:, 1].astype(float) # Cannot change datatype of a column

# data[data[:, 0] > 30, 1] *= 1.05     # cannot multiply int with float, inplace changes from int to float of one column not allowed

data[data[:, 0] > 30, 1] = (data[data[:, 0] > 30, 1] * 1.05).astype(float) 
# This is allowed as casting float to int is possible, Here float is casted back to int

print(type(data[:, 1][1]))




[[   35 60000]
 [   40 80000]]
[[   22 30000]
 [   28 45000]
 [   35 60000]
 [   40 80000]]
<class 'numpy.int64'>


### Task 8
    scores = np.array([45, 67, 82, 90, 55, 38])
    Select scores >= 60
    Replace scores < 50 with 0

In [65]:
scores = np.array([45, 67, 82, 90, 55, 38])

score_more_than_60 = scores[scores>=60] # short method--> create another array from original
print(score_more_than_60)
# x = scores>60                            # Create a variable
# more_score = scores[x]                   # Now create new array 
# print(more_score)
print(scores)

[67 82 90]
[45 67 82 90 55 38]


### Task 2
    employees = np.array([
        [25, 40000],
        [30, 50000],
        [35, 65000],
        [45, 80000]
    ])


    Select employees with salary > 60000

    Increase salary by 10% for age ≥ 40

In [79]:
employees = np.array([
        [25, 40000],
        [30, 50000],
        [35, 65000],
        [45, 80000]
    ])

emp_with_highsalary = employees[employees[:, 1]>60000]
print(emp_with_highsalary)

age = employees[:, 0]>=40
#employees[employees[:, 0]>=40, 1] *= 1.10  In place modification from int to float is not allowed
employees[employees[:, 0]>=40, 1] = (employees[employees[:, 0]>=40, 1]*1.10).astype(float) # Float is assigned back to int
#employees[age, 1] = (employees[age, 1]*1.1).astype(float)
print(employees)

[[   35 65000]
 [   45 80000]]
[[   25 40000]
 [   30 50000]
 [   35 65000]
 [   45 88000]]
