
### Task 1. 
Create a NumPy array for:

salaries = [40000, 50000, 60000, 70000]

Print: shape, number of dimensions, data type


In [2]:
import numpy as np

In [3]:
salaries = [40000, 50000, 60000, 70000]

salaries_np = np.array(salaries)
salaries_np
print(salaries_np.shape, salaries_np.ndim, salaries_np.dtype)

(4,) 1 int64


### Task 2

Create a 2D array representing:

[age, salary]
[23, 40000]
[28, 52000]
[35, 75000]

Print: array, shape, ndim

In [ ]:
# Think of it as --> rows: people (each person/row is represeted by age, salary), 
# columns: features (each column is a feature, two columns--age, salary)

age_salaries = np.array([[23, 40000], [28, 52000], [35, 75000]])
age_salaries

print(age_salaries.ndim, age_salaries.shape)

2 (3, 2)


### Task 3

Create an array of:

10 zeros

10 ones

In [10]:
arr_z1 = np.zeros(10)
print(arr_z1)
arr_o1 = np.ones(10)
arr_o1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Task 4

Create numbers from 5 to 50 with step 5

In [13]:
arr_arng = np.arange(5,51,5)
arr_arng

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

### Task 5

Create 8 evenly spaced values between 0 and 100

In [8]:
arr_ls = np.linspace(1, 100, 8)
arr_ls

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

### Task 4 (Real-World)

Simulate 30 days temperature data:
- Mean = 25°C, 
- Std deviation = 3°C

In [12]:
# simulating temperature for 30 days with mean of 25°C, and deviation of 3°C
arr_tmp = np.random.normal(loc=25, scale=3, size=30)
print(arr_tmp)

[20.59841751 19.76534602 25.07046764 20.88318456 28.87017203 28.85921118
 29.2435287  27.61867562 26.29143367 22.52735946 27.94706749 25.54800487
 21.61322752 28.76462727 26.29397127 27.04700987 28.83134174 27.47969336
 23.66678069 25.55861945 22.4112352  27.34628257 26.11436173 23.67477375
 22.46011594 28.80304046 24.74332785 25.86497016 23.90178816 26.61771868]


In [22]:
# 2 weeks × 7 days × 2 cities
arr_w_d_city = np.random.normal(25, 3, (2, 7, 2))
arr_w_d_city
#print(arr_w_d_city.shape, arr_w_d_city.ndim)

array([[[29.96286998, 21.72575917],
        [26.31360313, 25.52867899],
        [24.60009643, 20.3213681 ],
        [26.32186129, 23.6559888 ],
        [24.93065827, 22.13314125],
        [26.10503732, 21.97632861],
        [23.10446435, 30.35811251]],

       [[23.64888644, 27.6325188 ],
        [25.13484221, 20.64738716],
        [25.50269738, 25.1500457 ],
        [25.30011067, 28.7589618 ],
        [29.63236875, 30.82747268],
        [24.81182213, 23.55819209],
        [22.77495077, 26.42763145]]])

### Task 6

    Create:
    arr = np.array([5, 10, 15, 20, 25, 30])
    Get last 3 elements
    Get elements at even indices
    Replace values > 20 with 0

#### Boolean Indexing Returns a Copy, Not a View
    Its example is shown below
    

In [ ]:
# ------------------

a = np.array([1, 2, 3, 4, 5, 6, 7])
b = a[1:4]
b[0] = 99
print(a)

#------------------



[ 1 99  3  4  5  6  7]
[20 25 30]
[ 5 15 25]
[25 30]
[ 5 10 15 20  0  0]


In [ ]:
# Boolean Indexing Returns a Copy, Not a View

arr1 = np.array([5, 10, 15, 20, 25, 30])
sub_arr1 = arr1[arr1>20] # Gives a copy not view
sub_arr1[::] = 0
print(arr1[arr1>20])
print(arr1) # Therefore array is not changed!

[25 30]
[ 5 10 15 20 25 30]


In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[-3:])
print(arr[::2])
print(arr[arr>20]) 
# Here we are printing a slice-(in terms of condition/boolean-mask, ie only that part where condition is True) of an array
arr[arr>20] = 0
# Here we are modifying arr by providing mask-in place ie without creating its copy
print(arr)

[20 25 30]
[ 5 15 25]
[25 30]
[ 5 10 15 20  0  0]


### Task 7 (2D)
data = np.array([
    [18, 20000],
    [25, 30000],
    [40, 50000],
    [30, 40000]
])

    Extract all ages
    Extract all salaries
    Extract rows where age > 30

In [ ]:
data = np.array([
    [18, 20000],
    [25, 30000],
    [40, 50000],
    [30, 40000]
])
filtered = data[data[:, 0]>30] # gives copy of data
print(filtered)
# print(data[:,0])
# print(data[:,1])
# print(data[data[:,0]>30]) # This changes original data, as boolean condition is used to make changes in-place, not in a copy
print(data)

[[   40 50000]]
[[   18 20000]
 [   25 30000]
 [   40 50000]
 [   30 40000]]


### Boolean Indexing Returns a Copy, Not a View

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25     # mask is an array of True/False
sub_arr = arr[arr>25]  #  sub_arr = arr[arr>25] Creates a mask/copy of arr, so original array is not modifies
print(sub_arr)
print(mask)

print(arr[mask])
print(arr)

[30 40 50]
[False False  True  True  True]
[30 40 50]
[10 20 30 40 50]


In [ ]:
salaries = np.array([25000, 40000, 55000, 70000])
high_salary = salaries > 50000
print(salaries[high_salary])  # Printing slice of salary
print(salaries)

salaries[salaries < 50000] *= 1.10  # modifying salaries in place with boolean masking
print(salaries)

[55000 70000]
[25000 40000 55000 70000]


In [ ]:
data = np.array([
        [22, 30000],
        [28, 45000],
        [35, 60000],
        [40, 80000]
    ])

# Filter rows where salary > 50000
high_income = data[data[:, 1] > 50000]
print(high_income)  # Copy of data
print(data)   # original data

# Increase salary for age > 30

# data = data.astype(float) # changing datatype of complete 2d array is possible

# data[:, 1] = data[:, 1].astype(float) # Cannot change datatype of a column

# data[data[:, 0] > 30, 1] *= 1.05     # cannot multiply int with float, inplace changes from int to float of one column not allowed

data[data[:, 0] > 30, 1] = (data[data[:, 0] > 30, 1] * 1.05).astype(float) 
# This is allowed as casting float to int is possible, Here float is casted back to int

print(type(data[:, 1][1]))




[[   35 60000]
 [   40 80000]]
[[   22 30000]
 [   28 45000]
 [   35 60000]
 [   40 80000]]
<class 'numpy.int64'>


### Task 8
    scores = np.array([45, 67, 82, 90, 55, 38])
    Select scores >= 60
    Replace scores < 50 with 0

In [ ]:
scores = np.array([45, 67, 82, 90, 55, 38])

score_more_than_60 = scores[scores>=60] # short method--> create another array from original
print(score_more_than_60)
score_more_than_60[0] = 68
print(score_more_than_60)                   # As boolean mask created a copy, original score remain unchanged
# x = scores>60                            # Create a variable
# more_score = scores[x]                   # Now create new array 
# print(more_score)
print(scores)
scores[scores<50] = 0 # Inplace changes using boolean masking
print(scores)

[67 82 90]
[68 82 90]
[45 67 82 90 55 38]
[ 0 67 82 90 55  0]


### Task 9
    employees = np.array([
        [25, 40000],
        [30, 50000],
        [35, 65000],
        [45, 80000]
    ])


    Select employees with salary > 60000

    Increase salary by 10% for age ≥ 40

In [7]:
employees = np.array([
        [25, 40000],
        [30, 50000],
        [35, 65000],
        [45, 80000]
    ])

print(employees)
emp_with_highsalary = employees[employees[:, 1]>60000]
#print(emp_with_highsalary)

age = employees[:, 0]>=40

#employees[employees[:, 0]>=40, 1] *= 1.10  In place modification from int to float is not allowed

employees[employees[:, 0]>=40, 1] = (employees[employees[:, 0]>=40, 1]*1.10).astype(float) # Float is assigned back to int
# -- Here we are updating the 'row' which satisfies the condition, all other rows remains same

#employees[age, 1] = (employees[age, 1]*1.1).astype(float)
print(employees[employees[:, 0]>=40, 1])
print(employees[:, 0]>=40, 1)

print(employees)

[[   25 40000]
 [   30 50000]
 [   35 65000]
 [   45 80000]]
[88000]
[False False False  True] 1
[[   25 40000]
 [   30 50000]
 [   35 65000]
 [   45 88000]]


#### Vectorized Operations
- Perform math on entire arrays at once
- Understand broadcasting rules
- Eliminate loops from real-world code

In [ ]:
# Perform math on entire arrays at once
prices = np.array([100, 200, 300])
new_prices = prices * 1.10   # Not slicing
print(prices)
print(new_prices)
new_prices[0] = 0   
print(prices)                # price is not changed
print(new_prices)

[100 200 300]
[110. 220. 330.]
[100 200 300]
[  0. 220. 330.]


In [9]:
# Element-wise Math Operations

arr = np.array([1, 2, 3, 4, 5])
print(arr+10)
print(arr*2)
print(arr**2)
print(np.sqrt(arr))

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


#### Broadcasting (🔥 VERY IMPORTANT 🔥)

**What is Broadcasting?**
- Broadcasting allows NumPy to perform operations on arrays of **different shapes**.

In [11]:
# 1. Example 1: Scalar + Array

arr = np.array([10, 20, 30])
print(arr + 5)

[15 25 35]


In [10]:
# Example 2: Row-wise operation
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(data + np.array([1, 2, 3]))

[[11 22 33]
 [41 52 63]]


In [ ]:
data1 = np.array([
                [1, 2, 3],
                [4, 5, 6],
                [2, 2, 2]
                ])
data2 = np.array([1, 2, 3])  # Column-wise --> Row remains constant say row1(data1) and columns of this row will be added to data2 matrx
print(data2.shape)
data3 = np.array([[1], [2], [3]]) # Row-wise --> Column remains constant. data 3 has one column. So column of data1 remains constant say column1, 
# and this one column of data3 will be added to all columns of data1
print(data3.shape)

#print(data1+data2.T)
print("-----------------")
print(data1+data2)
print(data1+data3)

(3,)
(3, 1)
-----------------
[[2 4 6]
 [5 7 9]
 [3 4 5]]
[[2 3 4]
 [6 7 8]
 [5 5 5]]


#### Broadcasting Practice

**If the added array has shape (1, n) → applied to each row** ---> column-wise

**If the added array has shape (n, 1) → applied to each column** ----> row-wise

In [24]:
a = np.ones((3,3))
x = np.array([1, 2, 3]) 
print(a+x)
# 2,3,4
# 2,3,4
# 2,3,4
print(a+x.T)
print(a+x.reshape(3,1))
# 2, 2, 2
# 3, 3, 3
# 4, 4, 4

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [28]:
# 5️⃣ Real-World Example: Feature Scaling

data = np.array([
    [25, 50000],
    [30, 60000],
    [35, 70000]
], dtype=float)

means = data.mean(axis=0)
stds = data.std(axis=0)
print(means, stds)

normalised = (data-means)/stds
print(normalised)


[3.e+01 6.e+04] [4.08248290e+00 8.16496581e+03]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [ ]:
# Practice problem

data = np.array([
    [160, 55],   # height (cm), weight (kg)
    [170, 65],
    [180, 75],
    [190, 85]
], dtype=float)

# Compute the mean of each column
mean_of_data = data.mean(axis=0)   # Calculates mean per column
# Compute stds of each column
stds_of_data = data.std(axis=0)    # Calculates std per column
print(mean_of_data, stds_of_data)
# Compute normalised data
normalised_data = (data-mean_of_data)/stds_of_data # mean, and std are matrix which interact with data elementwise for each row
print(normalised_data)

# Check
print(normalised_data.mean(axis=0))
print(normalised_data.std(axis=0))

[175.  70.] [11.18033989 11.18033989]
[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
[0. 0.]
[1. 1.]


### Task 10: 

    prices = np.array([100, 200, 300, 400])
    
    Add 5% tax
    Apply ₹50 discount

In [43]:
prices = np.array([100, 200, 300, 400, 500])
# tax_prices = prices + (prices/100)*10
prices = prices*1.05-50
print(prices)
#print(tax_prices)

# discounted_price = tax_prices-50
# print(discounted_price)

[ 55. 160. 265. 370. 475.]


### Task 11: 
    data = np.array([
        [10, 20],
        [30, 40],
        [50, 60]
    ], dtype=float)

- Add [2, 5] to each row
- Multiply each row by [1, 2]


In [37]:
data = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
], dtype=float)

print(data+np.array([1,2]))

print(data*np.array([1,2]))



[[11. 22.]
 [31. 42.]
 [51. 62.]]
[[ 10.  40.]
 [ 30.  80.]
 [ 50. 120.]]


### Task 12 

    Normalize this data:

    scores = np.array([50, 60, 70, 80, 90], dtype=float)

In [41]:
scores = np.array([50, 60, 70, 80, 90], dtype=float)
mean_score = scores.mean()
score_std = scores.std()
normalized_scores = (scores-mean_score)/score_std
print(normalized_scores)
print(normalized_scores.mean())

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0


### Part 6


In [1]:
import numpy as np

### Aggregation
- Basic Aggregation(Without axis) Not used much jst for understanding

In [ ]:
# Basic Aggregation(Without axis) 
# rows = employees, columns = [age, salary, experience]

data = np.array([
    [25, 50000, 2],
    [30, 60000, 5],
    [35, 70000, 8],
    [40, 80000, 12]
], dtype=float)

print(data.sum())
print(data.mean())
print(data.min())
print(data.max())
# idx = data[:, 1].argmax()
# print(idx)        # index
# print(data[idx])  # full row
# print(data[0])

260157.0
21679.75
2.0
80000.0


- Column-wise Aggregation (axis=0) -- **stats per feature(per-column)**

In [ ]:
print(f"mean of [age, salary, experience]: {data.mean(axis=0)}")
# Gives average [age, salary, experience]
print(f"minimum of [age, salary, experience]: {data.min(axis=0)}")
print(f"maximum of [age, salary, experience]: {data.max(axis=0)}")
print(f"sum of [age, salary, experience]: {data.sum(axis=0)}")

mean of age, salary, experience: [3.25e+01 6.50e+04 6.75e+00]
minimum of age, salary, experience: [2.5e+01 5.0e+04 2.0e+00]
maximum of age, salary, experience: [4.0e+01 8.0e+04 1.2e+01]
sum of age, salary, experience: [1.3e+02 2.6e+05 2.7e+01]



- Row-wise Aggregation (axis=1) -- **stats per row/per employee data**

In [ ]:
print(f"mean of one employee data/per row ie mean of [age, salary, experience]: {data.mean(axis=1)}")
# Not of much use

mean of all employee data/per row ie mean of [age, salary, experience]: [16675.66666667 20011.66666667 23347.66666667 26684.        ]


In [ ]:
print(f"minimun of one employee data/per row ie min of [age, salary, experience]: {data.min(axis=1)}") 
# which will be age or experience, not of mucu use

minimun of one employee data/per row ie min of [age, salary, experience]: [ 2.  5.  8. 12.]


- argmax & argmin -- **Practical**

In [2]:
import numpy as np

# rows = employees, columns = [age, salary, experience]
data = np.array([
    [25, 50000, 2],
    [30, 60000, 5],
    [35, 70000, 8],
    [40, 80000, 12]
], dtype=float)

idx = data[:, 1].argmax()
#data[idx]
data[3]

array([4.0e+01, 8.0e+04, 1.2e+01])

### Part 7

In [3]:
data = np.array([
    [25, 50000, 2],
    [30, 60000, 5],
    [35, 70000, 8],
    [40, 80000, 12],
    [45, 90000, 15]
], dtype=float)

#### Task 1: Basic Analytics (Axis mastery)

    Compute column-wise:
    Mean
    Min
    Max
    Expected shape: (3,)

In [4]:
print(data.mean(axis=0))
print(data.min(axis=0))
print(data.max(axis=0))

[3.5e+01 7.0e+04 8.4e+00]
[2.5e+01 5.0e+04 2.0e+00]
[4.5e+01 9.0e+04 1.5e+01]


#### Task 2: Conditional Update (Boolean Masking)
    Rule:
    Employees with age > 35 get a 10% salary raise
    👉 Update data in place
    💡 Hint: boolean masking
    

In [ ]:
data[data[:, 0]>35, 1] *= 1.10
data
data.shape

#### Task 3: Add a New Feature (Reshape + Resize)

    Add a new column:
    bonus = 5% of salary
    👉 Final shape should be:
    (5, 4)

    💡 Hint:
    Compute bonus as 1D array
    Reshape to (n, 1)
    Use np.hstack

In [ ]:
bonus = data[:, 1]*0.05
b = bonus.reshape(5,1) # bonus.reshape(-1,1), we dont care about rows but need one column

bonus_arr = np.hstack((data, b))
bonus_arr

array([[2.5e+01, 5.0e+04, 2.0e+00, 2.5e+03],
       [3.0e+01, 6.0e+04, 5.0e+00, 3.0e+03],
       [3.5e+01, 7.0e+04, 8.0e+00, 3.5e+03],
       [4.0e+01, 8.0e+04, 1.2e+01, 4.0e+03],
       [4.5e+01, 9.0e+04, 1.5e+01, 4.5e+03]])

#### Task 4: Normalize Numeric Features (Broadcasting)

    Normalize only these columns:
    salary
    bonus
    Use Z-score normalization:
    (x - mean) / std

    📌 Do NOT normalize age or experience.

In [6]:
# Method 1. try to normalise one at a time

# data_mean = data[:,1].mean(axis=0)
# data_std = data[:, 1].std(axis=0)
# normalised_salary = (data[:, 1]-data_mean)/data_std
# normalised_salary

# data_mean = data[:,2].mean(axis=0)
# data_std = data[:, 2].std(axis=0)
# normalised_bonus = (data[:, 2]-data_mean)/data_std
# normalised_bonus

# Method 2: normalise both at a time
cols = [1, 2]
means = bonus_arr[:, cols].mean(axis=0)
stds = bonus_arr[:, cols].std(axis=0)
bonus_arr[:, cols] = (bonus_arr[:, cols]-means)/stds

In [7]:
print(bonus_arr)

[[ 2.50000000e+01 -1.41421356e+00 -1.36947358e+00  2.50000000e+03]
 [ 3.00000000e+01 -7.07106781e-01 -7.27532837e-01  3.00000000e+03]
 [ 3.50000000e+01  0.00000000e+00 -8.55920985e-02  3.50000000e+03]
 [ 4.00000000e+01  7.07106781e-01  7.70328887e-01  4.00000000e+03]
 [ 4.50000000e+01  1.41421356e+00  1.41226963e+00  4.50000000e+03]]


#### Task 5: Advanced Query (Real-world logic)
    Answer using one NumPy expression each:
    Total salary payout
    Employee index with max experience
    Average bonus of employees with age ≥ 35

In [ ]:
print(f"Total salary payout: {bonus_arr[:,3].sum(axis=0)}")

In [ ]:
idx = data[:,2].argmax()
print(idx)
print(f"Row of employee with max experience: {data[idx]}")

In [ ]:
# bonus_arr[:,0]>=35  --- this is mask, which give 1d array of T, F
# print(f"Average bonus of employees with age>=35: {bonus_arr[bonus_arr[:,0]>=35, 3]}") --Only T is applied to column 3

print(f"Average bonus of employees with age>=35: {bonus_arr[bonus_arr[:,0]>=35, 3].mean()}") # No need to use axis=0, as only col 3 is filteted

Average bonus of employees with age>=35: 4000.0
