In [2]:
import numpy as np

1. A 1D array of numbers from 0 to 9

In [7]:
arr_1d = np.arange(0,10)
arr_1d
# print(arr_1d.shape)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. A 3x3 matrix of all 5s

In [11]:
arr_2d = np.full((3,3), 5)
arr_2d

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

3. A 4x4 identity matrix

In [13]:
arr_I = np.eye(4,4)
arr_I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4. 10 evenly spaced numbers between 1 and 100

In [15]:
arr_ls = np.linspace(1, 100, 10)
arr_ls

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

5. A 2x2 array with random values between 0 and 1

In [17]:
arr_rd = np.random.rand(2,2)
arr_rd

array([[0.86261707, 0.62038412],
       [0.63536924, 0.62700072]])